### ISSUE TITLE
Code updates and new functionality

### ISSUE THREAD

**Issue by kwhiteaker** [ALTEMIS-DOE/pylenm#6]
- [x] fix supersmoother which does not work for certain wells
- [x] make pylenm use more general wording such that it can apply to surface water data, not just groundwater; ex. for functions like `interpolate_by_well`, create a duplicate function `interpolate_by_station` with the same functionality, and then once all relevant functions are duplicated & the duplicates all work together then we can remove the originals
- [ ] implement Kalman filter functionality, from Schmidt et al. https://pubs.acs.org/doi/abs/10.1021/acs.est.8b00017
- [x] Replace or remove `richdem` package dependency, as it appears to not be used much in the code other than under `install_requires` in setup.py, and it causes installation issues for some users on Windows e.g. https://github.com/r-barnes/richdem/issues/66

**Comment by satyarth934** [comment]
Suggestion for outlier - [RANSAC algorithm](https://en.wikipedia.org/wiki/Random_sample_consensus)
